In [9]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import statsmodels.api as sm
from ISLP.models import (ModelSpec as MS, summarize , poly)

HD=pd.read_csv('heart_disease_uci.csv')
cols_to_drop=['id','dataset']
HD_cleaned=HD.drop(columns=cols_to_drop)
dummycols=['sex','cp','restecg','slope','thal']
HD_cleaned=pd.get_dummies(HD_cleaned,columns=dummycols,drop_first=True)
HD_cleaned

,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,num,sex_Male,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,True,150.0,False,2.3,0.0,0,True,False,False,True,False,False,False,False,False,False
1,67,160.0,286.0,False,108.0,True,1.5,3.0,2,True,False,False,False,False,False,True,False,True,False
2,67,120.0,229.0,False,129.0,True,2.6,2.0,1,True,False,False,False,False,False,True,False,False,True
3,37,130.0,250.0,False,187.0,False,3.5,0.0,0,True,False,True,False,True,False,False,False,True,False
4,41,130.0,204.0,False,172.0,False,1.4,0.0,0,False,True,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,127.0,333.0,True,154.0,False,0.0,NaN,1,False,False,False,False,False,True,False,False,False,False
916,62,NaN,139.0,False,NaN,NaN,NaN,NaN,0,True,False,False,True,False,True,False,False,False,False
917,55,122.0,223.0,True,100.0,False,0.0,NaN,2,True,False,False,False,False,True,False,False,False,False
918,58,NaN,385.0,True,NaN,NaN,NaN,NaN,0,True,False,False,False,False,False,False,False,False,False
919,62,120.0,254.0,False,93.0,True,0.0,NaN,1,True,True,False,False,False,False,False,False,False,False

In [10]:
c=HD_cleaned.copy()

c['miss_trestbps']=np.where(np.isnan(c.trestbps)==True,1,0)

c_num=c.num
c=c.drop(columns=['trestbps','chol','fbs','thalch','exang','oldpeak','ca','num'])
c_num=np.array(c_num)
glm=sm.OLS(c_num,c.astype(float))
results = glm.fit()
summarize(results)

                            coef  std err       t  P>|t|
age                       0.0198    0.002  10.407  0.000
sex_Male                  0.3342    0.076   4.381  0.000
cp_atypical angina       -0.8661    0.085 -10.221  0.000
cp_non-anginal           -0.5784    0.080  -7.244  0.000
cp_typical angina        -0.6261    0.145  -4.329  0.000
restecg_normal           -0.2254    0.076  -2.965  0.003
restecg_st-t abnormality  0.0172    0.103   0.167  0.867
slope_flat                0.2486    0.079   3.137  0.002
slope_upsloping          -0.0714    0.094  -0.756  0.450
thal_normal              -0.2129    0.096  -2.216  0.027
thal_reversable defect    0.3801    0.087   4.358  0.000
miss_trestbps             0.3364    0.137   2.461  0.014

In [11]:
c=HD_cleaned.copy()

c['miss_chol']=np.where(np.isnan(c.chol)==True,1,0)

c_num=c.num
c=c.drop(columns=['trestbps','chol','fbs','thalch','exang','oldpeak','ca','num'])
c_num=np.array(c_num)
glm=sm.OLS(c_num,c.astype(float))
results = glm.fit()
summarize(results)

                            coef  std err       t  P>|t|
age                       0.0209    0.002  11.089  0.000
sex_Male                  0.3458    0.076   4.528  0.000
cp_atypical angina       -0.8739    0.085 -10.282  0.000
cp_non-anginal           -0.5658    0.080  -7.068  0.000
cp_typical angina        -0.6227    0.145  -4.292  0.000
restecg_normal           -0.2343    0.076  -3.078  0.002
restecg_st-t abnormality  0.0327    0.103   0.318  0.751
slope_flat                0.1944    0.077   2.525  0.012
slope_upsloping          -0.1196    0.093  -1.283  0.200
thal_normal              -0.2284    0.096  -2.367  0.018
thal_reversable defect    0.3627    0.088   4.143  0.000
miss_chol                -0.1425    0.177  -0.807  0.420

In [12]:
c=HD_cleaned.copy()

c['miss_fbs']=np.where(c.fbs.isnull()==True,1,0)

c_num=c.num
c=c.drop(columns=['trestbps','chol','fbs','thalch','exang','oldpeak','ca','num'])
c_num=np.array(c_num)
glm=sm.OLS(c_num,c.astype(float))
results = glm.fit()
summarize(results)

                            coef  std err       t  P>|t|
age                       0.0205    0.002  10.947  0.000
sex_Male                  0.3368    0.076   4.430  0.000
cp_atypical angina       -0.8436    0.085  -9.912  0.000
cp_non-anginal           -0.5540    0.080  -6.951  0.000
cp_typical angina        -0.6045    0.144  -4.188  0.000
restecg_normal           -0.2655    0.076  -3.481  0.001
restecg_st-t abnormality  0.0127    0.103   0.123  0.902
slope_flat                0.1950    0.076   2.552  0.011
slope_upsloping          -0.1521    0.093  -1.630  0.104
thal_normal              -0.1919    0.096  -1.994  0.046
thal_reversable defect    0.3917    0.087   4.492  0.000
miss_fbs                  0.3362    0.106   3.161  0.002

In [13]:
c=HD_cleaned.copy()

c['miss_thalch']=np.where(c.thalch.isnull()==True,1,0)

c_num=c.num
c=c.drop(columns=['trestbps','chol','fbs','thalch','exang','oldpeak','ca','num'])
c_num=np.array(c_num)
glm=sm.OLS(c_num,c.astype(float))
results = glm.fit()
summarize(results)

                            coef  std err       t  P>|t|
age                       0.0202    0.002  10.534  0.000
sex_Male                  0.3391    0.076   4.438  0.000
cp_atypical angina       -0.8713    0.085 -10.265  0.000
cp_non-anginal           -0.5750    0.080  -7.185  0.000
cp_typical angina        -0.6249    0.145  -4.312  0.000
restecg_normal           -0.2281    0.076  -2.993  0.003
restecg_st-t abnormality  0.0269    0.103   0.261  0.794
slope_flat                0.2293    0.079   2.892  0.004
slope_upsloping          -0.0889    0.095  -0.941  0.347
thal_normal              -0.2152    0.096  -2.235  0.026
thal_reversable defect    0.3784    0.088   4.323  0.000
miss_thalch               0.2179    0.141   1.541  0.124

In [14]:
c=HD_cleaned.copy()

c['miss_exang']=np.where(c.exang.isnull()==True,1,0)

c_num=c.num
c=c.drop(columns=['trestbps','chol','fbs','thalch','exang','oldpeak','ca','num'])
c_num=np.array(c_num)
glm=sm.OLS(c_num,c.astype(float))
results = glm.fit()
summarize(results)

                            coef  std err       t  P>|t|
age                       0.0202    0.002  10.534  0.000
sex_Male                  0.3391    0.076   4.438  0.000
cp_atypical angina       -0.8713    0.085 -10.265  0.000
cp_non-anginal           -0.5750    0.080  -7.185  0.000
cp_typical angina        -0.6249    0.145  -4.312  0.000
restecg_normal           -0.2281    0.076  -2.993  0.003
restecg_st-t abnormality  0.0269    0.103   0.261  0.794
slope_flat                0.2293    0.079   2.892  0.004
slope_upsloping          -0.0889    0.095  -0.941  0.347
thal_normal              -0.2152    0.096  -2.235  0.026
thal_reversable defect    0.3784    0.088   4.323  0.000
miss_exang                0.2179    0.141   1.541  0.124

In [15]:
c=HD_cleaned.copy()

c['miss_oldpeak']=np.where(c.oldpeak.isnull()==True,1,0)

c_num=c.num
c=c.drop(columns=['trestbps','chol','fbs','thalch','exang','oldpeak','ca','num'])
c_num=np.array(c_num)
glm=sm.OLS(c_num,c.astype(float))
results = glm.fit()
summarize(results)

                            coef  std err       t  P>|t|
age                       0.0200    0.002  10.493  0.000
sex_Male                  0.3330    0.076   4.355  0.000
cp_atypical angina       -0.8663    0.085 -10.205  0.000
cp_non-anginal           -0.5746    0.080  -7.192  0.000
cp_typical angina        -0.6292    0.145  -4.345  0.000
restecg_normal           -0.2285    0.076  -3.004  0.003
restecg_st-t abnormality  0.0176    0.103   0.171  0.865
slope_flat                0.2450    0.080   3.062  0.002
slope_upsloping          -0.0726    0.095  -0.762  0.446
thal_normal              -0.2203    0.096  -2.294  0.022
thal_reversable defect    0.3762    0.087   4.312  0.000
miss_oldpeak              0.2743    0.135   2.026  0.043

In [16]:
c=HD_cleaned.copy()

c['miss_ca']=np.where(np.isnan(c.ca)==True,1,0)

c_num=c.num
c=c.drop(columns=['trestbps','chol','fbs','thalch','exang','oldpeak','ca','num'])
c_num=np.array(c_num)
glm=sm.OLS(c_num,c.astype(float))
results = glm.fit()
summarize(results)

                            coef  std err       t  P>|t|
age                       0.0209    0.002  10.103  0.000
sex_Male                  0.3489    0.078   4.491  0.000
cp_atypical angina       -0.8766    0.085 -10.311  0.000
cp_non-anginal           -0.5681    0.080  -7.099  0.000
cp_typical angina        -0.6212    0.145  -4.279  0.000
restecg_normal           -0.2280    0.086  -2.663  0.008
restecg_st-t abnormality  0.0465    0.113   0.412  0.680
slope_flat                0.1964    0.078   2.531  0.012
slope_upsloping          -0.1203    0.096  -1.253  0.211
thal_normal              -0.2330    0.107  -2.178  0.030
thal_reversable defect    0.3596    0.095   3.776  0.000
miss_ca                  -0.0214    0.099  -0.216  0.829

Therefore, for this analysis we can use imputation to fill in missing values for MAR variables and, in order to simplify our analysis for comparison of our method across datasets, we can drop the MNAR variables (trestbps, fbs, and oldpeak).